-- MySQL Script generated by MySQL Workbench
-- 04/10/15 01:31:06
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Hospital
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Hospital` ;
CREATE SCHEMA IF NOT EXISTS `Hospital` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `Hospital` ;

-- -----------------------------------------------------
-- Table `Hospital`.`consultorio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Hospital`.`consultorio` ;

CREATE TABLE IF NOT EXISTS `Hospital`.`consultorio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rotulo` VARCHAR(2) NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hospital`.`tipopersonal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Hospital`.`tipopersonal` ;

CREATE TABLE IF NOT EXISTS `Hospital`.`tipopersonal` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hospital`.`recursohumano`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Hospital`.`recursohumano` ;

CREATE TABLE IF NOT EXISTS `Hospital`.`recursohumano` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `edad` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hospital`.`paciente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Hospital`.`paciente` ;

CREATE TABLE IF NOT EXISTS `Hospital`.`paciente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hospital`.`expediente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Hospital`.`expediente` ;

CREATE TABLE IF NOT EXISTS `Hospital`.`expediente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
